---
- name: install Windows Updates
  hosts: windowsserver
  gather_facts: yes
  
  tasks:
  - name: Install all security updates with automatic reboots
    win_updates:
      reboot: yes
  - name: Upgrade installed packages
    win_chocolatey:
      name: all
      state: latest
